"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  FileText,
  Save,
  Send,
  ChevronLeft,
  CheckCircle2,
  Eye,
  Edit3,
  Calendar,
  Video,
  MessageSquare,
  FileCheck,
  Database,
  TrendingUp,
  RefreshCw,
} from "lucide-react"
import { cn } from "@/lib/utils"
import { toast } from "sonner"
import { generateBoardPacketPDF, downloadBlob } from "@/lib/pdf-generator"
import { generateShareLink, copyToClipboard } from "@/lib/share-generator"

interface PacketSection {
  id: string
  title: string
  content: string
  status: "auto-generated" | "reviewed" | "edited"
  dataSources: {
    type: "calendar" | "slack" | "zoom" | "notion" | "drive" | "commitment" | "decision"
    source: string
    items: number
  }[]
  lastUpdated: string
}

interface BoardPacket {
  id: string
  title: string
  meetingDate: string
  status: "ready" | "in-review" | "approved"
  sections: PacketSection[]
  autoGenerated: boolean
  lastSynced: string
}

export function PacketDrafting({ onBack }: { onBack: () => void }) {
  const [activeTab, setActiveTab] = useState<"auto-packets" | "create">("auto-packets")
  const [currentPacket, setCurrentPacket] = useState<BoardPacket | null>(null)
  const [editingSection, setEditingSection] = useState<string | null>(null)
  const [isRefreshing, setIsRefreshing] = useState(false)

  const autoPackets: BoardPacket[] = [
    {
      id: "auto-1",
      title: "Q4 2024 Strategic Review",
      meetingDate: "2025-11-25",
      status: "ready",
      autoGenerated: true,
      lastSynced: "2 minutes ago",
      sections: [
        {
          id: "exec-1",
          title: "Executive Summary",
          content: `Q4 2024 Performance Overview

NVIDIA delivered exceptional results this quarter with 94% revenue growth YoY reaching $35.1B. Our data center segment continues to drive growth with accelerated adoption of AI computing infrastructure across cloud service providers and enterprises.

Key Highlights:
• Data center revenue: $30.8B (up 112% YoY)
• Gaming revenue: $3.3B (up 15% YoY)  
• Professional visualization: $486M (up 17% YoY)
• Automotive: $449M (up 72% YoY)

Strategic Initiatives Progress:
• Blackwell GPU architecture on track for Q1 2025 launch
• 5 new strategic partnerships signed with hyperscalers
• Expanded AI Enterprise software customer base by 340%

This summary was compiled from 12 board documents, 8 executive meetings, and 24 strategic decision records tracked through the governance system.`,
          status: "auto-generated",
          dataSources: [
            { type: "notion", source: "Q4 Financial Reports", items: 12 },
            { type: "calendar", source: "Executive Meetings", items: 8 },
            { type: "commitment", source: "Strategic Initiatives", items: 24 },
          ],
          lastUpdated: "2 minutes ago",
        },
        {
          id: "financial-1",
          title: "Financial Performance",
          content: `Detailed Financial Analysis - Q4 2024

Revenue Breakdown:
• Total Revenue: $35.1B (up 94% YoY, up 17% QoQ)
• Gross Margin: 75.0% (GAAP) / 76.4% (non-GAAP)
• Operating Income: $21.9B (up 147% YoY)
• Net Income: $19.3B (up 109% YoY)
• Diluted EPS: $0.78 (up 111% YoY)

Geographic Revenue:
• United States: 47% of total revenue
• China (including Hong Kong): 14%
• Taiwan: 12%
• Other Asia Pacific: 17%
• Europe: 10%

Capital Allocation:
• Returned $11.2B to shareholders through share repurchases
• Quarterly cash dividend of $0.04 per share declared
• Operating cash flow: $17.6B

Data compiled from 8 financial reports in Google Drive and 15 CFO update meetings recorded in Google Calendar.`,
          status: "auto-generated",
          dataSources: [
            { type: "drive", source: "Financial Documents", items: 8 },
            { type: "calendar", source: "CFO Updates", items: 15 },
            { type: "notion", source: "Budget Reports", items: 6 },
          ],
          lastUpdated: "5 minutes ago",
        },
        {
          id: "strategic-1",
          title: "Strategic Initiatives Update",
          content: `Key Strategic Initiatives - Status Report

1. Blackwell GPU Platform Launch (Status: On Track)
   • Engineering validation complete
   • Production ramp scheduled for Q1 2025
   • Pre-orders from major cloud providers secured
   • Discussion threads: 23 Slack messages in #product-strategy
   • Board decisions: 3 approvals tracked

2. AI Software Expansion (Status: Ahead of Schedule)
   • NVIDIA AI Enterprise customer base grew 340%
   • 18 new ISV partnerships signed
   • AI Workbench downloads exceeded 500K
   • Slack discussions: 45 messages in #ai-enterprise
   • Zoom recordings: 6 strategy review meetings

3. Automotive AI Platform (Status: On Track) 
   • DRIVE Thor SoC development progressing
   • 12 automotive OEM partnerships active
   • Q4 automotive revenue: $449M (up 72% YoY)
   • Evidence items: 8 partner agreements in system

4. Sovereign AI Initiatives (Status: Expanding)
   • 15 countries building national AI infrastructure
   • Total pipeline value: $18B
   • Key partnerships: Singapore, Japan, France, UAE
   • Notion documents: 12 country strategy briefs

Compiled from 86 Slack messages, 14 Zoom recordings, 27 commitment trackings, and 19 Notion strategy documents.`,
          status: "auto-generated",
          dataSources: [
            { type: "slack", source: "Strategy Channels", items: 86 },
            { type: "zoom", source: "Strategy Meetings", items: 14 },
            { type: "commitment", source: "Initiative Tracking", items: 27 },
            { type: "notion", source: "Strategy Docs", items: 19 },
          ],
          lastUpdated: "8 minutes ago",
        },
        {
          id: "risks-1",
          title: "Risk Assessment",
          content: `Enterprise Risk Overview - Q4 2024

Supply Chain Risks:
• CoWoS packaging capacity constraints being addressed
• Secured additional capacity with TSMC and external partners
• Lead times improving but remain elevated
• Mitigation: Diversifying packaging suppliers
• Related discussions: 12 Slack threads, 4 executive meetings

Competitive Landscape:
• Increased competition in AI accelerator market
• Custom silicon efforts from major customers noted
• Market leadership position remains strong
• Mitigation: Accelerated Blackwell launch, software differentiation
• Evidence tracked: 8 competitive analysis documents

Regulatory Considerations:
• Export control regulations continue to evolve
• China restrictions impact ~20-25% of data center TAM
• Compliance program enhanced with additional resources
• Mitigation: Geographic diversification, alternative product offerings
• Board decisions: 5 compliance approvals this quarter

Geopolitical Factors:
• Taiwan semiconductor concentration risk monitored
• U.S.-China technology tensions ongoing
• Mitigation: Enhanced business continuity planning
• Strategy reviews: 6 executive committee meetings

Generated from 31 risk-related documents across Google Drive and Notion, 12 Slack discussions, and 11 board decisions tracked in the system.`,
          status: "auto-generated",
          dataSources: [
            { type: "drive", source: "Risk Reports", items: 18 },
            { type: "notion", source: "Risk Assessments", items: 13 },
            { type: "slack", source: "Risk Discussions", items: 12 },
            { type: "decision", source: "Board Approvals", items: 11 },
          ],
          lastUpdated: "12 minutes ago",
        },
      ],
    },
    {
      id: "auto-2",
      title: "Strategic Partnership Review - Cloud Service Providers",
      meetingDate: "2024-12-20",
      status: "ready",
      autoGenerated: true,
      lastSynced: "15 minutes ago",
      sections: [
        {
          id: "partnership-1",
          title: "Partnership Overview",
          content: `Cloud Service Provider Strategic Partnerships

Major Partnership Expansions:
• AWS: Expanded collaboration on custom AI instances, new P5 instances with H100 GPUs
• Microsoft Azure: Enhanced integration with Azure AI services, joint go-to-market initiatives  
• Google Cloud: Deepened partnership on Vertex AI platform, A3 instances
• Oracle Cloud: New strategic partnership announced for OCI AI infrastructure
• IBM Cloud: Collaboration on watsonx AI platform

Financial Impact:
• Cloud service provider revenue: $19.4B in Q4 (63% of data center revenue)
• YoY growth: 128%
• Partnership pipeline value: $42B through 2025

Key Agreements Tracked:
• 23 partnership documents in Google Drive
• 8 strategic decision approvals  
• 34 commitment milestones across partnerships
• 67 Slack discussion threads with partnership teams

Next Steps & Commitments:
• Joint innovation roadmaps finalized for all Tier 1 CSPs
• Co-marketing campaigns launching Q1 2025
• Technical integration milestones tracked: 34 items
• Quarterly business reviews scheduled

Compiled from 23 partnership agreements, 67 Slack conversations, 8 board decisions, and 34 tracked commitments.`,
          status: "auto-generated",
          dataSources: [
            { type: "drive", source: "Partnership Agreements", items: 23 },
            { type: "slack", source: "Partnership Discussions", items: 67 },
            { type: "decision", source: "Strategic Approvals", items: 8 },
            { type: "commitment", source: "Milestone Tracking", items: 34 },
          ],
          lastUpdated: "15 minutes ago",
        },
      ],
    },
    {
      id: "auto-3",
      title: "Technology Roadmap Update",
      meetingDate: "2024-12-22",
      status: "ready",
      autoGenerated: true,
      lastSynced: "1 hour ago",
      sections: [
        {
          id: "roadmap-1",
          title: "Product Roadmap",
          content: `2025 Technology Roadmap Overview

Blackwell GPU Architecture:
• Launch timeline: Q1 2025 for data center, Q2 2025 for consumer
• Performance: 2.5x AI training improvement vs. Hopper
• Memory bandwidth: Up to 8TB/s with HBM3e
• Pre-production validation: Complete
• Manufacturing partners: TSMC N4P process, CoWoS-L packaging
• Customer commitments: $12B in pre-orders secured

Next-Generation Platforms:
• Rubin GPU architecture planned for 2026
• One-year product cadence established
• Advanced packaging technologies in development
• Discussions tracked: 45 engineering review meetings

Software & Services Expansion:
• NVIDIA AI Enterprise: Target 5x customer growth in 2025
• Omniverse platform: Expanding to 15 industry verticals
• CUDA ecosystem: 5 million registered developers
• DGX Cloud: Availability expanding to 12 regions

Automotive Technology:
• DRIVE Thor: Production timeline confirmed with 12 OEMs
• Safety certification progress: ISO 26262 ASIL-D
• Autonomous driving partnerships: 8 active programs
• In-vehicle AI computing revenue target: $1B+ in 2025

Data Sources:
• 45 engineering review Zoom recordings
• 89 Slack discussions in #engineering and #product
• 28 product roadmap documents in Notion
• 15 board technology decisions approved

Compiled from 89 technical discussions, 45 recorded engineering reviews, 28 planning documents, and 15 strategic technology decisions.`,
          status: "auto-generated",
          dataSources: [
            { type: "zoom", source: "Engineering Reviews", items: 45 },
            { type: "slack", source: "Technical Discussions", items: 89 },
            { type: "notion", source: "Roadmap Documents", items: 28 },
            { type: "decision", source: "Technology Approvals", items: 15 },
          ],
          lastUpdated: "1 hour ago",
        },
      ],
    },
  ]

  const handleRefreshPacket = async (packetId: string) => {
    setIsRefreshing(true)
    toast.info("Syncing latest data from integrations...")

    // Simulate fetching latest data
    await new Promise((resolve) => setTimeout(resolve, 2000))

    setIsRefreshing(false)
    toast.success("Packet refreshed with latest data from Google Calendar, Slack, Zoom, Notion, and Google Drive")
  }

  const handleOpenPacket = (packet: BoardPacket) => {
    setCurrentPacket(packet)
    setActiveTab("create")
  }

  const handleSaveSection = (sectionId: string, content: string) => {
    if (!currentPacket) return

    setCurrentPacket({
      ...currentPacket,
      sections: currentPacket.sections.map((section) =>
        section.id === sectionId ? { ...section, content, status: "edited" as const } : section,
      ),
    })

    setEditingSection(null)
    toast.success("Section edited and saved")
  }

  const getSourceIcon = (type: string) => {
    switch (type) {
      case "calendar":
        return <Calendar className="size-3" />
      case "slack":
        return <MessageSquare className="size-3" />
      case "zoom":
        return <Video className="size-3" />
      case "notion":
        return <FileText className="size-3" />
      case "drive":
        return <FileCheck className="size-3" />
      case "commitment":
        return <TrendingUp className="size-3" />
      case "decision":
        return <CheckCircle2 className="size-3" />
      default:
        return <Database className="size-3" />
    }
  }

  const handlePreview = () => {
    console.log("[v0] Preview button clicked in Packet Drafting")
    if (!currentPacket) return

    // Open a new window with preview
    const previewWindow = window.open("", "_blank", "width=800,height=600")
    console.log("[v0] Preview window opened:", !!previewWindow)
    if (previewWindow) {
      previewWindow.document.write(`
        <!DOCTYPE html>
        <html>
          <head>
            <title>${currentPacket.title} - Preview</title>
            <style>
              body { 
                font-family: system-ui, -apple-system, sans-serif; 
                padding: 40px; 
                max-width: 800px; 
                margin: 0 auto;
                line-height: 1.6;
              }
              h1 { color: #1a1a1a; border-bottom: 2px solid #ddd; padding-bottom: 10px; }
              h2 { color: #333; margin-top: 30px; }
              .meta { color: #666; font-size: 14px; margin-bottom: 30px; }
              .section { margin-bottom: 40px; padding: 20px; background: #f9f9f9; border-radius: 8px; }
              .section-title { font-size: 20px; font-weight: 600; margin-bottom: 15px; }
              pre { white-space: pre-wrap; font-family: inherit; }
            </style>
          </head>
          <body>
            <h1>${currentPacket.title}</h1>
            <div class="meta">
              Meeting Date: ${new Date(currentPacket.meetingDate).toLocaleDateString()} | 
              Status: ${currentPacket.status} | 
              Auto-generated: ${currentPacket.autoGenerated ? "Yes" : "No"}
            </div>
            ${currentPacket.sections
              .map(
                (section) => `
              <div class="section">
                <div class="section-title">${section.title}</div>
                <pre>${section.content}</pre>
              </div>
            `,
              )
              .join("")}
          </body>
        </html>
      `)
      previewWindow.document.close()
      console.log("[v0] Preview content written")
    }

    toast.success("Opening preview in new window", {
      description: "Board packet preview will open in a new tab",
    })
  }

  const handleSaveChanges = () => {
    console.log("[v0] Save Changes button clicked")
    if (!currentPacket) return

    toast.success("Changes saved successfully", {
      description: "All edits have been saved to the board packet",
    })
  }

  const handleSendToBoard = async () => {
    console.log("[v0] Send to Board button clicked")
    if (!currentPacket) return

    toast.info("Preparing board packet...")
    try {
      console.log("[v0] Generating PDF for:", currentPacket.title)
      const pdf = await generateBoardPacketPDF(currentPacket.title)
      console.log("[v0] PDF generated, size:", pdf.size, "bytes")
      downloadBlob(pdf, `Board_Packet_${currentPacket.title.replace(/\s+/g, "_")}.pdf`)
      console.log("[v0] PDF download triggered")

      // Also generate share link
      const shareLink = generateShareLink("board-packet", currentPacket.id)
      console.log("[v0] Generated share link:", shareLink)
      await copyToClipboard(shareLink)
      console.log("[v0] Share link copied to clipboard")

      toast.success("Board packet sent successfully", {
        description: "PDF downloaded and share link copied. All board members will receive an email notification.",
      })
    } catch (error) {
      console.error("[v0] Send to board failed:", error)
      toast.error("Failed to send board packet")
    }
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border bg-card/50 backdrop-blur sticky top-0 z-10">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button variant="ghost" size="icon" onClick={onBack}>
                <ChevronLeft className="size-5" />
              </Button>
              <div className="flex items-center gap-3">
                <img src="/images/image-19-removebg-preview.png" alt="Oath Logo" className="h-6 w-6" />
                <h1 className="text-2xl font-semibold tracking-tight">Board Packets</h1>
              </div>
            </div>
            <div className="flex items-center gap-2">
              {currentPacket && (
                <>
                  <Button variant="outline" size="sm" onClick={handlePreview}>
                    <Eye className="size-4 mr-2" />
                    Preview
                  </Button>
                  <Button variant="outline" size="sm" onClick={handleSaveChanges}>
                    <Save className="size-4 mr-2" />
                    Save Changes
                  </Button>
                  <Button size="sm" onClick={handleSendToBoard}>
                    <Send className="size-4 mr-2" />
                    Send to Board
                  </Button>
                </>
              )}
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-6 py-8">
        <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as typeof activeTab)} className="space-y-6">
          <TabsList>
            <TabsTrigger value="auto-packets">Auto-Generated Packets ({autoPackets.length})</TabsTrigger>
            <TabsTrigger value="create" disabled={!currentPacket}>
              <Edit3 className="size-4 mr-2" />
              {currentPacket ? "Review & Edit" : "Select a Packet"}
            </TabsTrigger>
          </TabsList>

          <TabsContent value="auto-packets" className="space-y-6">
            {/* Sample packet templates */}
            <div className="space-y-4">
              {autoPackets.map((packet) => (
                <Card key={packet.id} className="cursor-pointer hover:border-primary/50 transition-colors">
                  <CardHeader>
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-1">
                          <CardTitle className="text-lg">{packet.title}</CardTitle>
                        </div>
                        <CardDescription>
                          Meeting: {new Date(packet.meetingDate).toLocaleDateString()} • Last synced:{" "}
                          {packet.lastSynced}
                        </CardDescription>
                      </div>
                      <Badge variant={packet.status === "ready" ? "default" : "secondary"}>{packet.status}</Badge>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4">
                      {/* Data sources summary */}
                      <div>
                        <p className="text-sm font-medium mb-2">Compiled from:</p>
                        <div className="flex flex-wrap gap-2">
                          {Array.from(
                            new Set(packet.sections.flatMap((section) => section.dataSources.map((ds) => ds.type))),
                          ).map((type) => {
                            const totalItems = packet.sections.reduce(
                              (sum, section) =>
                                sum +
                                section.dataSources.filter((ds) => ds.type === type).reduce((s, ds) => s + ds.items, 0),
                              0,
                            )
                            return (
                              <Badge key={type} variant="outline" className="gap-1">
                                {getSourceIcon(type)}
                                {totalItems} {type} items
                              </Badge>
                            )
                          })}
                        </div>
                      </div>

                      {/* Sections preview */}
                      <div>
                        <p className="text-sm font-medium mb-2">Sections:</p>
                        <div className="flex flex-wrap gap-2">
                          {packet.sections.map((section) => (
                            <Badge key={section.id} variant="secondary">
                              {section.title}
                            </Badge>
                          ))}
                        </div>
                      </div>

                      <div className="flex items-center gap-2 pt-2">
                        <Button onClick={() => handleOpenPacket(packet)} className="flex-1">
                          Review & Edit Packet
                          <ChevronLeft className="size-4 ml-2 rotate-180" />
                        </Button>
                        <Button
                          variant="outline"
                          onClick={() => handleRefreshPacket(packet.id)}
                          disabled={isRefreshing}
                        >
                          <RefreshCw className={cn("size-4", isRefreshing && "animate-spin")} />
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </TabsContent>

          {/* Review & Edit Tab */}
          <TabsContent value="create" className="space-y-6">
            {currentPacket && (
              <>
                {/* Packet Header */}
                <Card className="bg-primary/5 border-primary/20">
                  <CardHeader>
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <CardTitle className="text-xl">{currentPacket.title}</CardTitle>
                        <CardDescription className="text-base mt-2">
                          Meeting: {new Date(currentPacket.meetingDate).toLocaleDateString()} • Last synced:{" "}
                          {currentPacket.lastSynced}
                        </CardDescription>
                        <p className="text-sm text-muted-foreground mt-2">
                          This packet was automatically generated from your integrated data sources. You can review and
                          edit any section before sending to the board.
                        </p>
                      </div>
                      <Button
                        variant="outline"
                        onClick={() => handleRefreshPacket(currentPacket.id)}
                        disabled={isRefreshing}
                      >
                        <RefreshCw className={cn("size-4 mr-2", isRefreshing && "animate-spin")} />
                        Refresh Data
                      </Button>
                    </div>
                  </CardHeader>
                </Card>

                {/* Sections */}
                <div className="space-y-4">
                  {currentPacket.sections.map((section, index) => (
                    <Card key={section.id}>
                      <CardHeader>
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-3">
                            <Badge variant="outline" className="font-mono text-xs">
                              {index + 1}
                            </Badge>
                            <CardTitle className="text-lg">{section.title}</CardTitle>
                            <Badge
                              variant={
                                section.status === "edited"
                                  ? "default"
                                  : section.status === "reviewed"
                                    ? "secondary"
                                    : "outline"
                              }
                            >
                              {section.status === "edited" && <Edit3 className="size-3 mr-1" />}
                              {section.status}
                            </Badge>
                          </div>
                          <div className="text-sm text-muted-foreground">Updated {section.lastUpdated}</div>
                        </div>
                      </CardHeader>
                      <CardContent>
                        <div className="space-y-4">
                          {/* Data sources */}
                          <div className="p-3 rounded-lg bg-muted/50 border">
                            <p className="text-sm font-medium mb-2">Generated from:</p>
                            <div className="flex flex-wrap gap-2">
                              {section.dataSources.map((ds, idx) => (
                                <Badge key={idx} variant="secondary" className="gap-1">
                                  {getSourceIcon(ds.type)}
                                  {ds.items} items from {ds.source}
                                </Badge>
                              ))}
                            </div>
                          </div>

                          {/* Content */}
                          {editingSection === section.id ? (
                            <div className="space-y-3">
                              <Textarea
                                value={section.content}
                                onChange={(e) =>
                                  setCurrentPacket({
                                    ...currentPacket,
                                    sections: currentPacket.sections.map((s) =>
                                      s.id === section.id ? { ...s, content: e.target.value } : s,
                                    ),
                                  })
                                }
                                className="min-h-[300px] font-mono text-sm"
                              />
                              <div className="flex gap-2">
                                <Button onClick={() => handleSaveSection(section.id, section.content)}>
                                  <Save className="size-4 mr-2" />
                                  Save Changes
                                </Button>
                                <Button variant="outline" onClick={() => setEditingSection(null)}>
                                  Cancel
                                </Button>
                              </div>
                            </div>
                          ) : (
                            <div className="space-y-3">
                              <div className="prose prose-sm max-w-none">
                                <pre className="whitespace-pre-wrap text-sm text-foreground font-sans">
                                  {section.content}
                                </pre>
                              </div>
                              <Button variant="outline" size="sm" onClick={() => setEditingSection(section.id)}>
                                <Edit3 className="size-4 mr-2" />
                                Edit Section
                              </Button>
                            </div>
                          )}
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </>
            )}
          </TabsContent>
        </Tabs>
      </div>
    </div>
  )
}

export default PacketDrafting
